Traceback (most recent call last):
  File "C:/Users/rabin/PycharmProjects/Automate-the-boring-stuff/Debugging/error.py", line 4, in <module>
    raise Exception("This is the error message")
Exception: This is the error message
Traceback (most recent call last):
  File "C:/Users/rabin/PycharmProjects/Automate-the-boring-stuff/Debugging/error.py", line 4, in <module>
    raise Exception("This is the error message")
Exception: This is the error message
